// Contract address - replace with your deployed contract address
export const FARM_ESCROW_ADDRESS = "0x1a932a833416b1ce95dd3623c2766df6f096d033";

// Contract ABI - using your original ABI
export const FARM_ESCROW_ABI = [
  // ABI from your contract
  {
    type: "constructor",
    inputs: [
      { name: "developerWallet", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "addProduct",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "category", type: "string", internalType: "string" },
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "stockQuantity", type: "uint256", internalType: "uint256" },
      { name: "unit", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "imageUrls", type: "string[]", internalType: "string[]" },
      { name: "isOrganic", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addShippingInfo",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "trackingInfo", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addToCart",
    inputs: [
      { name: "productId", type: "uint256", internalType: "uint256" },
      { name: "quantity", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "autoNotifyEscrowClaimable",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "buyerOrders",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimEscrow",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "clearCart",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createOrderFromCart",
    inputs: [
      { name: "shippingAddress", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "createUserProfile",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "contactInfo", type: "string", internalType: "string" },
      { name: "location", type: "string", internalType: "string" },
      { name: "bio", type: "string", internalType: "string" },
      { name: "isSeller", type: "bool", internalType: "bool" },
      { name: "farmName", type: "string", internalType: "string" },
      { name: "farmDescription", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getCartItems",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct FarmEscrow.CartItem[]",
        components: [
          { name: "productId", type: "uint256", internalType: "uint256" },
          { name: "quantity", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCartTotal",
    inputs: [],
    outputs: [{ name: "total", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEscrowDetails",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "developerFee", type: "uint256", internalType: "uint256" },
      { name: "sellerAmount", type: "uint256", internalType: "uint256" },
      { name: "isReleased", type: "bool", internalType: "bool" },
      { name: "isRefunded", type: "bool", internalType: "bool" },
      { name: "isClaimable", type: "bool", internalType: "bool" },
      { name: "isClaimed", type: "bool", internalType: "bool" },
      { name: "releasedAt", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrderDetails",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "buyer", type: "address", internalType: "address" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "productIds", type: "uint256[]", internalType: "uint256[]" },
      { name: "quantities", type: "uint256[]", internalType: "uint256[]" },
      { name: "totalPrice", type: "uint256", internalType: "uint256" },
      { name: "shippingFee", type: "uint256", internalType: "uint256" },
      {
        name: "status",
        type: "uint8",
        internalType: "enum FarmEscrow.OrderStatus",
      },
      { name: "shippingAddress", type: "string", internalType: "string" },
      { name: "trackingInfo", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlatformStats",
    inputs: [],
    outputs: [
      { name: "totalVolume", type: "uint256", internalType: "uint256" },
      { name: "totalOrders", type: "uint256", internalType: "uint256" },
      { name: "developerFees", type: "uint256", internalType: "uint256" },
      { name: "activeProducts", type: "uint256", internalType: "uint256" },
      { name: "activeUsers", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProduct",
    inputs: [{ name: "productId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct FarmEscrow.Product",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "name", type: "string", internalType: "string" },
          { name: "category", type: "string", internalType: "string" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "stockQuantity", type: "uint256", internalType: "uint256" },
          { name: "unit", type: "string", internalType: "string" },
          { name: "description", type: "string", internalType: "string" },
          { name: "imageUrls", type: "string[]", internalType: "string[]" },
          { name: "isAvailable", type: "bool", internalType: "bool" },
          { name: "isOrganic", type: "bool", internalType: "bool" },
          { name: "soldCount", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProductsByCategory",
    inputs: [{ name: "category", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSellerOrders",
    inputs: [{ name: "seller", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserOrders",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserProducts",
    inputs: [{ name: "seller", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateCartItemQuantity",
    inputs: [
      { name: "productId", type: "uint256", internalType: "uint256" },
      { name: "newQuantity", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateOrderStatus",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      {
        name: "newStatus",
        type: "uint8",
        internalType: "enum FarmEscrow.OrderStatus",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateProduct",
    inputs: [
      { name: "productId", type: "uint256", internalType: "uint256" },
      { name: "name", type: "string", internalType: "string" },
      { name: "category", type: "string", internalType: "string" },
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "stockQuantity", type: "uint256", internalType: "uint256" },
      { name: "unit", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "imageUrls", type: "string[]", internalType: "string[]" },
      { name: "isAvailable", type: "bool", internalType: "bool" },
      { name: "isOrganic", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateUserProfile",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "contactInfo", type: "string", internalType: "string" },
      { name: "location", type: "string", internalType: "string" },
      { name: "bio", type: "string", internalType: "string" },
      { name: "farmName", type: "string", internalType: "string" },
      { name: "farmDescription", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "userProfiles",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "contactInfo", type: "string", internalType: "string" },
      { name: "location", type: "string", internalType: "string" },
      { name: "bio", type: "string", internalType: "string" },
      { name: "isVerified", type: "bool", internalType: "bool" },
      { name: "rating", type: "uint256", internalType: "uint256" },
      { name: "reviewCount", type: "uint256", internalType: "uint256" },
      { name: "isSeller", type: "bool", internalType: "bool" },
      { name: "farmName", type: "string", internalType: "string" },
      { name: "farmDescription", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
] as const;

// Helper function to get contract instance
export function getFarmEscrowContract() {
  return {
    address: FARM_ESCROW_ADDRESS,
    abi: FARM_ESCROW_ABI,
  } as const;
}
